name: CI/CD Security Scan on Juice Shop

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  juice-shop-security:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Juice Shop Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Start Juice Shop App in Background
      run: |
        npm start &           # Run app in background
        sleep 15              # Wait for it to fully start

    - name: Set up Python (for Semgrep)
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install Semgrep
      run: pip install semgrep

    - name: Run Semgrep Scan (SAST)
      run: semgrep scan --config auto --error

    - name: Run OWASP ZAP Baseline Scan (DAST)
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://localhost:3000'
        fail_action: true
        allow_issue_writing: false
        token: ${{ secrets.GITHUB_TOKEN }}
