name: CI/CD Security Scan on Juice Shop

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Start Juice Shop in Docker
      run: docker run -d -p 3000:3000 --name juice-shop bkimminich/juice-shop

    - name: Wait for Juice Shop to Start
      run: sleep 15

    - name: Install Python (for Semgrep)
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Semgrep
      run: pip install semgrep

    - name: Run Semgrep Scan (SAST)
      run: |
        semgrep scan --config auto || true

    - name: Run OWASP ZAP Baseline Scan (DAST)
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://localhost:3000'
        fail_action: false
        token: ${{ secrets.GITHUB_TOKEN }}
